---

- name: Create missing locales
  become: true
  command: locale-gen en_GB.UTF-8

- name: set locale
  become: true
  action: command update-locale LC_ALL=en_GB.utf8

- name: Add terminal to unity bar
  copy:
    src: files/scripts/startup_config.sh
    dest: /home/vagrant/bin/
    owner: vagrant
    group: vagrant
    mode: 0744

- name: gnomerc runs on desktop startup, then runs script above
  copy:
    src: files/scripts/.gnomerc
    dest: /home/vagrant/.gnomerc
    owner: vagrant
    group: vagrant
    mode: 0744


